<?php
/**
 * Inject some CKEditor templates
 */
function wl_ckeditor_plugins_init() {
  drupal_add_js(array(
    'wl_ckeditor_plugins' => array(
      'base_path' => drupal_get_path('module', 'wl_ckeditor_plugins') . '/plugins/ckeditor'
    )
  ), 'setting');

  drupal_add_js(drupal_get_path('module', 'wl_ckeditor_plugins') . '/plugins/ckeditor/wl_templates/plugin.js', array(
    'type' => 'file',
    'scope' => 'footer',
    'weight' => 100,
    'every_page' => true,
  ));
}